version: "3.2"
services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  api:
    build: .
    ports:
      - "9080:9080"
    entrypoint: [ "python", "app.py" ]
    depends_on:
      - redis
  celery:
    build: .
    entrypoint: [ "celery", "-A", "app.celery_app", "worker", "-l", "debug"]
    depends_on:
      - redis
